<?php
/**
 * ACF helper functions
 */

// change / add to the base background choices here
$background_choices_available = array (
	'none' 		=> 'No background',
	'inverse' 	=> 'Inverse',
	'bright'	=> 'Bright background',
);

$color_theme_list = array (
	'default-theme' 		=> 'Default',
	'retrorocket-theme' 	=> 'Retro Rocket',
	'boldnblue-theme'		=> 'Bold n Blue',
	'youthful-theme'		=> 'Youthful',
);

$nav_font_choices = array(
	'Roboto:wght@500' => '"Roboto", sans-serif',
	'Montserrat:wght@400' => '"Montserrat", sans-serif',
	'Poppins:wght@500' => '"Poppins", sans-serif',
	'Barlow+Condensed:wght@500' => '"Barlow Condensed", sans-serif',
	'Hind:wght@500' => '"Hind", sans-serif',
	'Trispace:wght@400' => '"Trispace", sans-serif',
	'Josefin+Slab:wght@500' => '"Josefin Slab", serif',
	'Noto+Serif:wght@700' => '"Noto Serif", serif',
	'Walter+Turncoat' => '"Walter Turncoat", cursive',
);

$heading_font_choices = array(
	'Montserrat:ital,wght@0,200;0,900;1,200;1,900' => '"Montserrat", sans-serif',
	'Roboto:ital,wght@0,100;0,700;1,100;1,700' => '"Roboto", sans-serif',
	'Work+Sans:ital,wght@0,200;0,800;1,200;1,800' => '"Work Sans", sans-serif',
	'Poppins:ital,wght@0,200;0,700;1,200;1,700' => '"Poppins", sans-serif',
	'Barlow+Condensed:ital,wght@0,200;0,700;1,200;1,700' => '"Barlow Condensed", sans-serif',
	'Hind:wght@300;700' => '"Hind", sans-serif',
	'Trispace:wght@200;800' => '"Trispace", sans-serif',
	'Cormorant+Garamond:ital,wght@0,300;0,700;1,300;1,700' => '"Cormorant Garamond", serif',
	'Josefin+Slab:ital,wght@0,200;0,700;1,200;1,700' => '"Josefin Slab", serif',
	'Architects+Daughter' => '"Architects Daughter", cursive',
	'Gaegu:wght@300;700' => '"Gaegu", cursive',
	'Nanum+Pen+Script' => '"Nanum Pen Script", cursive',
);

$body_font_choices = array(
	'Roboto+Condensed:ital,wght@0,300;0,700;1,300;1,700' => '"Roboto Condensed", sans-serif',
	'Roboto:ital,wght@0,300;0,900;1,300;1,900' => '"Roboto", sans-serif',
	'Work+Sans:ital,wght@0,300;0,800;1,300;1,800' => '"Work Sans", sans-serif',
	'Montserrat:ital,wght@0,300;0,800;1,300;1,800' => '"Montserrat", sans-serif',
	'Poppins:ital,wght@0,300;0,800;1,300;1,800' => '"Poppins", sans-serif',
	'Noto+Serif:ital,wght@0,400;0,700;1,400;1,700' => '"Noto Serif", serif',
	'Cormorant+Garamond:ital,wght@0,500;0,700;1,500;1,700' => '"Cormorant Garamond", serif',
	'Josefin+Slab:ital,wght@0,400;0,700;1,400;1,700' => '"Josefin Slab", serif',
	'Gaegu:wght@400;700' => '"Gaegu", cursive',
);



// settings on where the 'sections' are active throughout the site
$where_sections_are_active = array (
	array (
		array (
			'param' => 'post_type',
			'operator' => '==',
			'value' => 'page',
		),
	),
/*	add any additional post types here. 
	array (
		array (
			'param' => 'post_type',
			'operator' => '==',
			'value' => 'person',
		),
	),
*/
);


//***************************************   SITE OPTIONS
if( function_exists('acf_add_local_field_group') ):
	acf_add_local_field_group(array (
		'key' => 'group_57f7c88c9aa18',
		'title' => 'Site Options',
		'fields' => array (
			array (
				'key' => 'field_57fbf3676e7e9',
				'label' => 'Display Options',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),

			array(
				'key' => 'field_5a1f1b703a28e',
				'label' => 'Site Logo',
				'name' => 'site_logo',
				'type' => 'image',
				'instructions' => 'Add a logo image for the header. If none, the site name will show in large text.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => 'jpg, gif, svg, png',
			),

			array (
				'key' => 'field_57f7c92167a96',
				'label' => 'Default Featured Image',
				'name' => 'default_post_thumbnail_id',
				'type' => 'image',
				'instructions' => 'If set, this image will be displayed as the featured image for any posts that don\'t have their own custom featured images.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array (
				'key' => 'field_57fc43235c0d0',
				'label' => 'Excerpt Settings',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Settings below determine how automatically generated post excerpts (aka blurbs) are displayed: how long they should be, and what text (if any) should be appended to the excerpt as a link to the post itself.',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array (
				'key' => 'field_57fbf44a6e7f0',
				'label' => 'Length',
				'name' => 'excerpt_length',
				'type' => 'number',
				'instructions' => 'Set to 0 to revert to WordPress\'s default (55 words), or to allow another plugin to trim excerpts.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '40',
					'class' => '',
					'id' => '',
				),
				'default_value' => 40,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_57fbf4686e7f1',
				'label' => 'Units',
				'name' => 'excerpt_length_unit',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'words' => 'Words',
					'chars' => 'Characters',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'words',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_57fc42c5a2686',
				'label' => 'Link Text',
				'name' => 'excerpt_link_text',
				'type' => 'text',
				'instructions' => 'e.g. \'Read more\'. Leave blank for no link.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '40',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Read more',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),

			array (
				'key' => 'field_5a1d8a764a977',
				'label' => 'Theme Design',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),


			array (
				'key' => 'field_1235890588717657',
				'label' => 'Theme Design',
				'name' => 'color_theme_or_custom_choice',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '40',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'color_theme' => 'Choose from library',
					'custom' => 'Custom',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'color_theme',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),

			array (
				'key' => 'field_12358ec5338e2191',
				'label' => 'Theme library',
				'name' => 'color_theme',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_1235890588717657',
							'operator' => '==',
							'value' => 'color_theme',
						),
					),
				),
				'wrapper' => array (
					'width' => '60',
					'class' => '',
					'id' => '',
				),
				'choices' => $color_theme_list,
				'default_value' => array (
					0 => 'none',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),

			array(
				'key' => 'field_5ff4c898f375b',
				'label' => 'Page Header',
				'name' => 'page_header_design',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_1235890588717657',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5ff4c8fef375c',
						'label' => 'Header background color',
						'name' => 'header_background_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#ffffff',
					),
					array(
						'key' => 'field_5ff4c9aaf375d',
						'label' => 'Header text color',
						'name' => 'header_text_color',
						'type' => 'color_picker',
						'instructions' => 'If no site logo is added, your site name will be this color.

Make sure this text color is readable on your header background color',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#1864ab',
					),
					array(
						'key' => 'field_5ff4caa6f375e',
						'label' => 'Top navigation bar background color',
						'name' => 'top_navigation_bar_background_color_choice',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '30',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'none' => 'Same as page header',
							'custom' => 'Custom color',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => 'none',
						'layout' => 'horizontal',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5ff4e46ac33be',
						'label' => 'Top nav bar background',
						'name' => 'top_nav_bar_background',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5ff4caa6f375e',
									'operator' => '==',
									'value' => 'custom',
								),
							),
						),
						'wrapper' => array(
							'width' => '70',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
					),
				),
			),
			array(
				'key' => 'field_5ff4cbff13392',
				'label' => 'Top Navigation Bar',
				'name' => 'top_navigation_bar_options',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_1235890588717657',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5ff4cc3113393',
						'label' => 'Nav item background color',
						'name' => 'nav_item_background_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#d0ebff',
					),
					array(
						'key' => 'field_5ff4cc8713394',
						'label' => 'Nav item text color',
						'name' => 'nav_item_text_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#1864ab',
					),
					array(
						'key' => 'field_5ff4cca613395',
						'label' => 'Hover background color',
						'name' => 'nav_item_hover_background_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#1864ab',
					),
					array(
						'key' => 'field_5ff4ccaa13396',
						'label' => 'Hover text color',
						'name' => 'nav_item_hover_text_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#d0ebff',
					),
					array(
						'key' => 'field_5ff4db6b13397',
						'label' => 'Nav item font',
						'name' => 'nav_item_font',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'choices' => $nav_font_choices,
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'array',
						'ajax' => 0,
						'placeholder' => '',
					),
				),
			),
			array(
				'key' => 'field_5ff4dc2bb571b',
				'label' => 'Page Body',
				'name' => 'page_body_design',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_1235890588717657',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5ff4dc3db571c',
						'label' => 'Page background color',
						'name' => 'page_background_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#ffffff',
					),
					array(
						'key' => 'field_5ff4dcc4b571d',
						'label' => 'Text color',
						'name' => 'page_text_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#212529',
					),
					array(
						'key' => 'field_5ff4dd00b571e',
						'label' => 'Link color',
						'name' => 'page_link_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#1864ab',
					),
					array(
						'key' => 'field_5ff4dd12b571f',
						'label' => 'Link hover color',
						'name' => 'page_link_hover_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#5f3dc4',
					),
					array(
						'key' => 'field_5ff4dd3bb5720',
						'label' => 'Body text font',
						'name' => 'body_text_font',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '80',
							'class' => '',
							'id' => '',
						),
						'choices' => $body_font_choices,
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'array',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5ff4dd9ab5721',
						'label' => 'Default size',
						'name' => 'body_text_default_size',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => 21,
						'placeholder' => '',
						'prepend' => '',
						'append' => 'pt',
						'min' => 12,
						'max' => 30,
						'step' => -13,
					),
					array(
						'key' => 'field_5ff4e24dcff0b',
						'label' => 'Heading text font',
						'name' => 'page_heading_text_font',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '80',
							'class' => '',
							'id' => '',
						),
						'choices' => $heading_font_choices,
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'array',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5ff4e29dcff0c',
						'label' => 'Bold page title?',
						'name' => 'bold_page_title',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'Yes' => 'Yes',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'vertical',
						'toggle' => 0,
						'return_format' => 'value',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5ff4ddddb5722',
						'label' => 'Primary button: background color',
						'name' => 'primary_button_background_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#d9480f',
					),
					array(
						'key' => 'field_5ff4de19b5723',
						'label' => 'Primary button: text color',
						'name' => 'primary_button_text_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#ffffff',
					),
					array(
						'key' => 'field_5ff4de32b5724',
						'label' => 'Primary button: hover background color',
						'name' => 'primary_button_hover_background_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#a61e4d',
					),
					array(
						'key' => 'field_5ff4de64b5725',
						'label' => 'Primary button: hover text color',
						'name' => 'primary_button_hover_text_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#ffffff',
					),

					array(
						'key' => 'field_115ff4ddddb5722',
						'label' => 'Secondary button: background color',
						'name' => 'secondary_button_background_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#4dabf7',
					),
					array(
						'key' => 'field_115ff4de19b5723',
						'label' => 'Secondary button: text color',
						'name' => 'secondary_button_text_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#ffffff',
					),
					array(
						'key' => 'field_115ff4de32b5724',
						'label' => 'Secondary button: hover background color',
						'name' => 'secondary_button_hover_background_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#20c997',
					),
					array(
						'key' => 'field_115ff4de64b5725',
						'label' => 'Secondary button: hover text color',
						'name' => 'secondary_button_hover_text_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#ffffff',
					),
				),
			),
			array(
				'key' => 'field_5ff4deb389975',
				'label' => 'Page Footer',
				'name' => 'page_footer_design',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_1235890588717657',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5ff4deb389976',
						'label' => 'Footer background color',
						'name' => 'footer_background_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#212529',
					),
					array(
						'key' => 'field_5ff4deb389977',
						'label' => 'Footer text color',
						'name' => 'footer_text_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#ced4da',
					),
					array(
						'key' => 'field_5ff4deb389978',
						'label' => 'Footer link color',
						'name' => 'footer_link_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#d0ebff',
					),
					array(
						'key' => 'field_5ff4deb389979',
						'label' => 'Footer link hover color',
						'name' => 'footer_link_hover_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#ced4da',
					),
				),
			),

			array (
				'key' => 'field_57fbf37a6e7ea',
				'label' => 'Text',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_57f7ceae82de8',
				'label' => 'Contact Info',
				'name' => 'contact_info',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array (
				'key' => 'field_57fbf4cf6e7f2',
				'label' => 'Copyright Text',
				'name' => 'copyright_text',
				'type' => 'text',
				'instructions' => 'The text <code>[year]</code> will be replaced with the current year.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Copyright © [year]. All rights reserved.',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57fbf39a6e7eb',
				'label' => 'URLs',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_57f7ca2067a98',
				'label' => 'Social Media Links',
				'name' => 'social_links',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_57f7ca3567a99',
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => 'Add Service',
				'sub_fields' => array (
					array (
						'key' => 'field_57f7ca3567a99',
						'label' => 'Service',
						'name' => 'service',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array (
							'facebook' => 'Facebook',
							'flickr' => 'Flickr',
							'googleplus' => 'Google+',
							'instagram' => 'Instagram',
							'linkedin' => 'LinkedIn',
							'pinterest' => 'Pinterest',
							'snapchat' => 'Snapchat',
							'tumblr' => 'Tumblr',
							'twitter' => 'Twitter',
							'youtube' => 'YouTube',
						),
						'default_value' => array (
						),
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'ajax' => 0,
						'return_format' => 'value',
						'placeholder' => '',
					),
					array (
						'key' => 'field_57f7cb1267a9b',
						'label' => 'Link Text',
						'name' => 'link_text',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'e.g. "Like us on Facebook", or "@MyOrg"',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array (
						'key' => 'field_57f7caee67a9a',
						'label' => 'URL',
						'name' => 'url',
						'type' => 'url',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
				),
			),
			array (
				'key' => 'field_57fbf3ab6e7ec',
				'label' => 'Integrations/API Keys',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_57f7d17269b71',
				'label' => 'Facebook App ID',
				'name' => 'facebook_app_id',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57f7ca0467a97',
				'label' => 'Google Maps API Key',
				'name' => 'google_maps_api_key',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'start-site-options',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
		'modified' => 1476826847,
	));


endif;

//***************************************   HOMEPAGE HERO
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5ffb4910c80e3',
		'title' => 'Homepage Hero',
		'fields' => array(
			array(
				'key' => 'field_5ffb491e4917c',
				'label' => 'Description',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'This is space exclusive to the home / first page of your site. This shows one large photo (the "featured image" of this page) with text and buttons positioned over the top of the image. You can edit or turn off any content areas in the settings below.',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_5ffb4a264917d',
				'label' => 'Large title text',
				'name' => 'large_title_text',
				'type' => 'text',
				'instructions' => 'The main, and largest text over the image. This should be very short!',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5ffb4b2a4917e',
				'label' => 'Secondary text',
				'name' => 'secondary_text',
				'type' => 'textarea',
				'instructions' => 'This text will show up below the large title text. This should still be pretty short--only a few sentences at most.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => 'wpautop',
			),
			array(
				'key' => 'field_5ffb4ba94917f',
				'label' => 'Call to action button(s)',
				'name' => 'call_to_action_buttons',
				'type' => 'repeater',
				'instructions' => 'You can add up to three "call to action" buttons. These show up under the large and secondary text above. 

There are two types of buttons: a primary button that will most likely be more prominent in design, and a secondary button that will most likely show up more subtle. A third choice is given of a simple text link, which will be less prominent than both.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 3,
				'layout' => 'row',
				'button_label' => 'Add a button',
				'sub_fields' => array(
					array(
						'key' => 'field_5ffb4ca149180',
						'label' => 'Label',
						'name' => 'cta_label',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'Button or link text',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ffb4cd949181',
						'label' => 'Link',
						'name' => 'cta_link',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
					),
					array(
						'key' => 'field_5ffb4d2849182',
						'label' => 'Style',
						'name' => 'cta_style',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'primary' => 'Primary',
							'secondary' => 'Secondary',
							'text_link' => 'Plain text link',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => '',
						'layout' => 'vertical',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
				),
			),
			array(
				'key' => 'field_5ffb4da449183',
				'label' => 'Layout options',
				'name' => 'layout_options',
				'type' => 'group',
				'instructions' => 'Below are some options for the layout and size of the hero section',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5ffb4df249184',
						'label' => 'Height',
						'name' => 'hero_height',
						'type' => 'radio',
						'instructions' => 'The default is for this hero section to stretch for almost the entire height of your browser screen. If you want this to be shorter/take up less space, set that here',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'full-height' => 'Full height (default)',
							'two-thirds-height' => '2/3 height',
							'one-half-height' => '1/2 height',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => 'full-height',
						'layout' => 'horizontal',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5ffb4ec249185',
						'label' => 'Text position (horizontal)',
						'name' => 'hero_text_position_horizontal',
						'type' => 'radio',
						'instructions' => 'Depending on the featured image, choose which side is best to display the text.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'left-side' => 'Left side',
							'right-side' => 'Right side',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => 'right-side',
						'layout' => 'horizontal',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5ffb4f9549186',
						'label' => 'Text position (vertical)',
						'name' => 'hero_text_position_vertical',
						'type' => 'radio',
						'instructions' => 'Now what is the best vertical placement?',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'align-top' => 'Near the top',
							'align-middle' => 'In the middle',
							'align-bottom' => 'Near the bottom',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => 'align-middle',
						'layout' => 'horizontal',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5ffb500f49187',
						'label' => 'Text color (optional)',
						'name' => 'hero_text_color',
						'type' => 'color_picker',
						'instructions' => 'If the contrast of the text over your featured image is too light, set a better color for the text here so it will show up clearly over the image.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#292929',
					),
					array(
						'key' => 'field_5ffb50c149188',
						'label' => 'Add a background (optional)',
						'name' => 'add_a_background',
						'type' => 'select',
						'instructions' => 'If the text is still hard to read over the image, you can add a semi-transparent background color to the text area. Choose between a light or dark background.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'bg-none' => 'No background (default)',
							'light-background' => 'Light background',
							'dark-background' => 'Dark background',
						),
						'default_value' => 'bg-none',
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_type',
					'operator' => '==',
					'value' => 'front_page',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

endif;